/** 검색 폼 자동완성용 주요 공항 (IATA 코드) */
export const AIRPORTS = [
  { code: "ICN", name: "인천" },
  { code: "GMP", name: "김포" },
  { code: "PUS", name: "김해(부산)" },
  { code: "CJU", name: "제주" },
  { code: "TAE", name: "대구" },
  { code: "CJJ", name: "청주" },
  { code: "NRT", name: "도쿄 나리타" },
  { code: "HND", name: "도쿄 하네다" },
  { code: "KIX", name: "오사카 간사이" },
  { code: "FUK", name: "후쿠오카" },
  { code: "CTS", name: "삿포로 신치토세" },
  { code: "OKA", name: "오키나와" },
  { code: "TPE", name: "타이베이 타오위안" },
  { code: "HKG", name: "홍콩" },
  { code: "PVG", name: "상하이 푸둥" },
  { code: "BKK", name: "방콕 수완나품" },
  { code: "DAD", name: "다낭" },
  { code: "SGN", name: "호치민" },
  { code: "HAN", name: "하노이" },
  { code: "CEB", name: "세부" },
  { code: "MNL", name: "마닐라" },
  { code: "SIN", name: "싱가포르" },
  { code: "KUL", name: "쿠알라룸푸르" },
  { code: "GUM", name: "괌" },
  { code: "SPN", name: "사이판" },
  { code: "CDG", name: "파리 샤를드골" },
  { code: "LHR", name: "런던 히스로" },
  { code: "FRA", name: "프랑크푸르트" },
  { code: "FCO", name: "로마" },
  { code: "BCN", name: "바르셀로나" },
  { code: "JFK", name: "뉴욕 JFK" },
  { code: "LAX", name: "로스앤젤레스" },
  { code: "SFO", name: "샌프란시스코" },
  { code: "HNL", name: "호놀룰루" },
  { code: "SYD", name: "시드니" },
] as const;
